version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python api.py

volumes:
  app-data: